#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
NC='\033[0m'

keys=1

echo ""

while test $# -gt 0
do
    case "$1" in 
        -h | --help)
            echo -e "${YELLOW}OPTIONS${NC}"
            echo -e "   -h, --help      this page"
            echo -e "   -n, --no-keys   start process WITHOUT keyboard client"
            exit 0
            shift
            ;;
        -n | --no-keys)
            keys=0
            shift
            ;;
        *)
            shift
            ;;
    esac
done

echo -e "${GREEN}[$(date +"%T")]${NC} starting node server @ http://$(ifconfig wlp3s0 | grep netmask | cut -d " " -f 10):4001"

if [[ keys -eq 1 ]]
then
    cd express
    node server.js > /dev/null 2>&1 &
    cd ..

    echo -e "${GREEN}[$(date +"%T")]${NC} starting keyboard client"
    ./clients/keyboard_client.py 
else
    cd express
    node server.js
fi